version: '3'
services:
  tiny-mongo:
     image: mongo
     container_name: tiny-mongo
     volumes:
      - '.docker-volumes/mongo/data:/data/db'
      - '$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/'
     ports:
      - 27017:27017
     env_file:
      - .env  
  tiny-redis:
    image: redis
    container_name: tiny-redis
    env_file:
      - .env
    ports:
      - 6379:6379   
    command: >
      --requirepass ${REDIS_PASSWORD}
  tiny-backend:
    image: registry.cn-shenzhen.aliyuncs.com/cpm_tiny/tiny:0.0.1
    container_name: tiny-backend
    ports:
     - 7003:7001
    env_file:
      - .env 
    restart: always  