name: Tag
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'test github context info'
        run: |
          echo ${{github.ref}}
          echo ${{github.ref_name}}
          echo ${{github.sha}}
      - name: replace tag
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '{{tag}}'
          replace: ${{github.ref_name}}
          include: 'docker-compose-prod.yml'
      - run: cat docker-compose-prod.yml
